# Generated by Django 2.2.6 on 2019-11-15 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endereco', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('resourcebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.ResourceBase')),
                ('name', models.CharField(help_text='Nome pelo qual sera chamado o evento', max_length=50)),
                ('date', models.DateTimeField(help_text='Data que foi criado o evento', null=True)),
                ('start_date', models.DateTimeField(help_text='Data que começa o evento', null=True)),
                ('end_date', models.DateTimeField(help_text='Data em que terminara o evento', null=True)),
                ('title', models.CharField(default='', help_text='Titulo do evento', max_length=40)),
                ('short_description', models.CharField(help_text='Pequeno resumo do evento', max_length=500)),
                ('description', models.TextField(default='', help_text='Corpo do html com as informações do evento')),
                ('image_file', models.FileField(default='', help_text='Imagem do evento', upload_to='events')),
                ('ticket_price', models.FloatField(default=0.0, help_text='Preço de cada cupom')),
                ('price', models.DecimalField(decimal_places=0, default=0.0, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('id_hash', models.TextField(default='149cd899-a020-4870-aee8-fb93f348d3bc', unique=True)),
                ('address', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endereco.Endereco')),
                ('upload_session', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento.UploadSession')),
            ],
            options={
                'db_table': 'eve_evento',
            },
            bases=('base.resourcebase',),
        ),
    ]
