# Generated by Django 2.2.6 on 2019-11-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(default='', unique=True)),
                ('description', models.TextField(default='')),
                ('fa_class', models.CharField(default='fa-times', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='Público', max_length=255)),
                ('description', models.TextField(default='')),
                ('fa_class', models.CharField(default='fa-times', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Types',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, help_text='Categoria a qual o evento se encaixa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.TopicCategory')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_base.resourcebase_set+', to='contenttypes.ContentType')),
                ('type_event', models.ForeignKey(blank=True, help_text='Tipo do evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.TopicType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
