# Generated by Django 2.2.6 on 2019-11-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'est_estado',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ibge_code', models.CharField(max_length=20)),
                ('sigla', models.CharField(default='', max_length=10)),
                ('estado', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cidade.Estado')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cid_cidade',
                'ordering': ['-name'],
            },
        ),
    ]
