# Generated by Django 2.2.6 on 2019-11-15 11:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 11, 15, 9, 41, 33, 308009))),
                ('value', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço de cada ticket', max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Desconto sobre o ticket se houver', max_digits=20)),
                ('final_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor final do ticket já com o desconto', max_digits=20)),
                ('is_paid', models.BooleanField(default=True, help_text='Se a ordem foi paga ou não')),
            ],
            options={
                'db_table': 'ord_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('event', models.ForeignKey(default=22, null=True, on_delete=django.db.models.deletion.PROTECT, to='evento.Evento')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'order_event',
            },
        ),
    ]
