# Generated by Django 2.2.6 on 2019-11-15 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191115_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 11, 34, 16, 969479)),
        ),
    ]
