# Generated by Django 2.2.6 on 2019-11-24 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191124_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 10, 43, 11, 682560)),
        ),
    ]
