# Generated by Django 2.2.6 on 2019-12-06 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20191206_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 18, 0, 36, 753704)),
        ),
    ]
