# Generated by Django 2.2.6 on 2019-12-08 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191206_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 9, 27, 48, 74569)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='key',
            field=models.CharField(default='b1873528-18a7-4603-b6f2-b8f3f3a4c949', help_text='Chave atualizado do ticket', max_length=16, unique=True),
        ),
    ]
