# Generated by Django 2.2.6 on 2019-12-08 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20191208_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 9, 32, 57, 43783)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='key',
            field=models.CharField(default='7b3812f819ae11ea', help_text='Chave atualizado do ticket', max_length=16, unique=True),
        ),
    ]
