# Generated by Django 2.2.6 on 2019-11-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(help_text='Nome de Rua, Avenida, Rodovia', max_length=200)),
                ('cep', models.CharField(help_text='Cep da Rua, Avenida, Rodovia', max_length=12)),
                ('number', models.IntegerField(help_text='Numero da Rua, Avenida, Rodovia')),
                ('city', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cidade.Cidade')),
            ],
            options={
                'db_table': 'end_endereco',
            },
        ),
    ]
